// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VChip: typeof import('vuetify/lib')['VChip']
    VFadeTransition: typeof import('vuetify/lib')['VFadeTransition']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VMain: typeof import('vuetify/lib')['VMain']
    VSelect: typeof import('vuetify/lib')['VSelect']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VTab: typeof import('vuetify/lib')['VTab']
    VTabItem: typeof import('vuetify/lib')['VTabItem']
    VTabs: typeof import('vuetify/lib')['VTabs']
    VTabsItems: typeof import('vuetify/lib')['VTabsItems']
    VTabsSlider: typeof import('vuetify/lib')['VTabsSlider']
    VTooltip: typeof import('vuetify/lib')['VTooltip']
  }
}

export {}
